"""Пермишены добавлены в бд

Revision ID: 4f0b76efa3ee
Revises: 9df95598735f
Create Date: 2026-01-01 16:06:12.990963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f0b76efa3ee'
down_revision: Union[str, Sequence[str], None] = '9df95598735f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('permissions', sa.ARRAY(sa.Enum('READ_USERS_DB', name='permission', native_enum=False)), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'permissions')
    # ### end Alembic commands ###
